### PR TITLE
Recreate branch and added Mockup and Readme

### PR DESCRIPTION
**Pull request by MishaKoval**
I delete old branches and create new PR

### CODE REVIEW

**Review by katetushkan — COMMENTED** [review]
.

**Review by katetushkan — APPROVED** [review]

**Review by katetushkan — CHANGES_REQUESTED** [review]
According to my notes, your topic is defined as 'Managing tools', innit?

**Comment by MishaKoval** [comment]
Yes

**Comment by katetushkan** [comment]
So not a 'todo' then. I expect you to push mockups according to your topic.

**Comment by MishaKoval** [comment]
I thought "like Trello" meant a to-do list

**Comment by MishaKoval** [comment]
And I making a todo list 😐

**Comment by katetushkan** [comment]
And you mock-up is nothing like Trello. You either update them accordingly to represent Trello-like functions, or I don't know what =)

**Comment by MishaKoval** [comment]
So the point is the same. Removing and adding cards with a list of tasks

**Comment by katetushkan** [comment]
If u are doing time-management like Trello, u need to change ur function list, like creating stages of the process, changing their statuses, drag'n'drop and so on. If u are just having list of tasks than it's to-do, that's not a management app) So if u picked up management app topic, so please upgrade ur function's criteria and mock up. Cuz rn it has  nothing to do w/ managing.)

**Comment by MishaKoval** [comment]
I change mockup and readme to time-management app like Trello

**Review by katetushkan — APPROVED** [review]
<kbd>7</kbd>.

**Comment by katetushkan** [comment]
> I change mockup and readme to time-management app like Trello

good boy.

**Pull request merged**
