### PR TITLE
Add mockup and html/css

### PR DESCRIPTION
**Pull request by MishaKoval**

### CODE REVIEW

**Review by katetushkan — CHANGES_REQUESTED** [review]
1st. It should be two different pr.
2nd. Add html tags on top of ur mockup.
3rd. Where is the other screens?
4th. I'll check html/css (the 3rd lab) only after I'll approve the 2nd. 

P.S. To pass html/css u. need a deploy link

**Comment by MishaKoval** [comment]
1st. It should be two different pr.
Now its different pr or i dont understand something?

**Comment by MishaKoval** [comment]
Or you about different pr to mockup and HTML/CSS?

**Comment by katetushkan** [comment]
> Or you about different pr to mockup and HTML/CSS?

yess.

**Pull request closed without merging**
